public class BiodataGagahEka {
    public static void main(String[] args){
        System.out.println("------------------");
        System.out.println("-- Biodata Saya --");
        System.out.println("------------------");
        System.out.println("Nama\t : Gagah Irlangsa Eka Yuanata");
        System.out.println("NIM\t : 244107060076");
        System.out.println("Kelas\t : 1B");
        System.out.println("Jurusan\t : Teknologi Informasi");
        System.out.println("Prodi\t : D-IV Sistem Informasi Bisnis");
        System.out.println("Alamat\t : Dwiga Regency A6/26");
    }
}